---
- name: print distribution name and version
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Load a variable file based on the OS type
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Apache
  include_tasks: "apache-{{ ansible_os_family }}.yml"

- name: ensure apache is running and enabled
  service:
    name: "{{ apache_package_name }}"
    state: started
    enabled: true

- name: ensure index.html is present
  template:
    src: index.html.j2
    dest: "/var/www/html/index.html"
