---
- name: print distribution name and version
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Load a variable file based on the OS type
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Apache on Debian-based distributions
  block:
    - name: ensure apache is installed (Debian-based)
      apt:
        name: "{{ apache_package_name }}"
        state: present
  when: ansible_os_family == 'Debian'

- name: Install Apache on RedHat-based distributions
  block:
    - name: ensure apache is installed (RedHat-based)
      yum:
        name: "{{ apache_package_name }}"
        state: present
  when: ansible_os_family == 'RedHat'

- name: ensure apache is running and enabled
  service:
    name: "{{ apache_package_name }}"
    state: started
    enabled: true

- name: ensure index.html is present
  template:
    src: index.html.j2
    dest: "/var/www/html/index.html"
