---
- name: ensure Apache2 is installed
  yum:
    name: httpd
    state: present

- name: ensure apache is running and enabled
  service:
    name: httpd
    state: started
    enabled: true

- name: ensure index.html is present
  copy:
    src: index.html
    dest: "/var/www/html/index.html"
